language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

#----------추가 부분------
before_script:
  - cd hello-spring (1)/freeled-springboot2-webservice/
  - pwd
#----------------------

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hansun33@naver.com